default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres
  host: localhost

development:
  <<: *default
  database: thequestion_development

test:
  <<: *default
  database: thequestion_development

production:
  <<: *default
  database: thequestion_development
